project:
  type: book
  output-dir: docs
  resources:
    - /reports/gpfg-data-audit.md
    - /images/Rlogo.png
    - /images/douban.png
    - /images/grp-summarize-01.mp4
    - /images/grp-summarize-02.mp4
    - /images/grp-summarize-03.mp4
    - /images/install-r-rstudio.png
    - /images/left-join.gif
    - /images/rmarkdown.png
    - /images/rstudio-ide.png
    - /images/tidyr-pivoting.gif
    - /cheatsheets/rmarkdown.pdf
    - /cheatsheets/rstudio-ide.pdf

book:
  title: "Data Journalism with R"
  author: "Bin Chen"
  date: last-modified
  page-footer: "Copyright © 2026 Bin Chen"
  search: true
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - install.qmd
        - r-basics.qmd
    - part: "Data Import & Cleaning"
      chapters:
        - data-import.qmd
        - data-wrangling.qmd
    - part: "Data Analysis"
      chapters:
        - analysis-gpfg.qmd
        - transform-merge.qmd
    - part: "Data Visualization"
      chapters:
        - visual-01.qmd
        - visual-02.qmd
        - map-gpfg.qmd
    - part: "Case Studies"
      chapters:
        - hot100.qmd
        - olympics.qmd
        - employment.qmd
        - debate.qmd
  appendices:
    - links.qmd
    - quarto.qmd
    - debug.qmd
    - final_project_notes.qmd
    - additional-practice.qmd
    - references.qmd

bibliography: references.bib

execute:
  warning: false
  message: false

format:
  html:
    theme: cosmo
    df-print: paged
    code-overflow: wrap
    code-copy: true
    number-depth: 2
    toc-depth: 3

editor: source
