project:
  type: book
  output-dir: docs
  resources:
    - v*/

book:
  title: "Data Journalism with R"
  author: "Bin Chen"
  date: last-modified
  page-footer: "Copyright © 2025 Bin Chen"
  search: true
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
      - install.qmd
      - r-basics.qmd
    - part: "Data Import & Wrangling"
      chapters:
      - data-import.qmd
      - data-wrangling.qmd
      - transform-merge.qmd
    - part: "Data Analysis"
      chapters:
      - analysis-hksalary.qmd
      - analysis-lifex.qmd
    - part: "Data Visualization"
      chapters:
      - visual-01.qmd
      - visual-02.qmd
      - map-lifex.qmd
      - norway-invest.qmd
    - part: "Special Topics"
      chapters:
      - quarto-pub.qmd
      - debate.qmd
    - part: "Case Studies"
      chapters:
      - hot100.qmd
      - olympics.qmd
      - employment.qmd
      - map-usa-election.qmd
    - part: "Appendix"
      chapters:
      - links.qmd
      
      

bibliography: references.bib


format:
  html:
    theme: cosmo
    df-print: paged
    code-overflow: wrap
    number-depth: 2



editor: source



