# Useful Links

## Software
- [Download R](https://www.r-project.org/)
- [Download RStudio](https://posit.co/download/rstudio-desktop/)
- [Download Quarto](https://quarto.org/docs/get-started/)
- [GitHub Pages documentation](https://docs.github.com/en/pages)
- [Posit Connect Cloud](https://connect.posit.cloud/)

## Where to find data news?

- [Caixin 財新-數字說](https://datanews.caixin.com/)
- [Initium Media 端傳媒-數洞](https://theinitium.com/column/data)
- [SCMP Infographics](https://www.scmp.com/infographic/)
- [The New York Times – The Upshot](https://www.nytimes.com/section/upshot)  
- [Reuters Data](https://www.reuters.com/data/)
- [Financial Times – Visual & Data Journalism](https://www.ft.com/visual-and-data-journalism)  
- [Our World in Data](https://ourworldindata.org)
- [NBC - The Data Point](https://www.nbcnews.com/datagraphics)
- [The Marshall Project](https://www.themarshallproject.org/)

## Where to find datasets?

- [DATA.GOV.HK](https://data.gov.hk/en/)
- [Census and Statistics Department (HK)](https://www.censtatd.gov.hk/)
- [Kaggle Datasets](https://www.kaggle.com/datasets)
- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [Our World in Data](https://ourworldindata.org)
- [World Bank Data](https://data.worldbank.org/)
- [United Nations Data Portal](https://data.un.org/)
- [OECD Data](https://data.oecd.org/)
- [Eurostat](https://ec.europa.eu/eurostat)
- [U.S. Government Open Data (data.gov)](https://www.data.gov/)
- [Humanitarian Data Exchange](https://data.humdata.org/)
- [IMF Data Portal](https://data.imf.org/)
- 💡[Global Investigative Journalism Network's list of databases](https://gijn.org/topic/databases/) 

::: callout-warning
Synthetic data can be useful for learning code, but it should not be reported as
evidence about the real world. Survey data can support strong journalism when
the sampling frame, questionnaire, weighting, field dates, response rate, and
uncertainty are available. Prefer authoritative publishers and read the
methodology before using either microdata or published estimates.
:::

## R Learning
- [R for Data Science, 2nd edition](https://r4ds.hadley.nz/)
- [ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/)
- [R Graphics Cookbook, 2nd edition](https://r-graphics.org/)
- [R for Journalists](https://r-journalism.com/)

## Data Journalism Guides

- [Introduction to Investigative Journalism: Data Journalism](https://gijn.org/resource/introduction-investigative-journalism-data-journalism/)
- [4 Common Angles Data Journalists Use to Tell Stories](https://gijn.org/stories/4-common-angles-data-journalists-use-to-tell-stories/)
- [From Data to Storytelling: Concept and Design Tips from the Financial Times’ John Burn-Murdoch](https://gijn.org/stories/data-visualization-storytelling-tips-john-burn-murdoch/)
- 


